### ISSUE TITLE
Review updates for how to test kernels in proposed guide

### ISSUE THREAD

**Issue by AnneCYH** [canonical/kernel-docs#11]
Hi @nwager 

Could you please help to review the changes made to this document?
[How to test kernels in -proposed](https://canonical-kernel-docs.readthedocs-hosted.com/en/latest/how-to/testing-verification/test-kernel-in-proposed/).

Some of the changes made:

- Updated some of the headings to be more explicit to help with SEO efforts. Currently "how to build an Ubuntu kernel" doesn't return any results from Read the Docs.
- Reworded the headings to be action-oriented (e.g. "Test the kernel" vs "Testing the kernel").
- Fixed some (what I think are) typos.
- Added links to relevant references like Linux Selftests page.
- Removed the part indicating that the document was based on the original Wiki. I added the Wiki as a "Related topic"; that should be sufficient.

Help needed:
- There seems to be something missing for the 23.10 instructions for [enabling the -proposed repo sources via CLI](https://canonical-kernel-docs.readthedocs-hosted.com/en/latest/how-to/testing-verification/test-kernel-in-proposed/#enable-the-proposed-pocket-via-cli). Which file needs to be added / changed for non-x86 architectures?

Lemme know if you have any questions, thanks!

Notes: This is ported over from https://canonical-kteam-docs.readthedocs-hosted.com/en/public/how-to/test-kernel-proposed.html.

CC @khbecker

**Comment by nwager** [comment]
All the fixes look good to me. I added a couple more details I thought would be helpful, and I fixed the sources.list instruction for pre-noble non-x86 systems. The PR can be found here: https://github.com/canonical/kernel-docs/pull/39
