### ISSUE TITLE
Review updates for how to build kernel

### ISSUE THREAD

**Issue by AnneCYH** [canonical/kernel-docs#2]
Hi @khbecker ,

Could you please help to review the changes made to this document?
[How to build an Ubuntu Linux kernel](https://canonical-kernel-docs.readthedocs-hosted.com/en/latest/how-to/build-publish/build-kernel/).

Some of the changes made:
1. The page title is more explicit to help with SEO efforts. Currently "how to build an Ubuntu kernel" doesn't return any results from Read the Docs.
2. Reworded some paragraphs to make certain instructions more explicit (including stating it's built locally) and to include straightforward samples to make it easy to follow. Especially for the part about modifying the ABI number.
3. Pointed to a simplified version of "How to obtain kernel source for an Ubuntu release using Git" instead of the Wiki version. The current how-to contains only the necessary information to complete the how-to-build-a-kernel guide. The wiki is still referenced.
4. Added some wording to the "Modify the kernel" section. Hope it makes it clearer on what will happen and that no 'copying' is needed.
5. Added an explicit (but optional) step to "Customise the kernel" which is basically when you would apply patches.
6. Added an "Explanation" page to describe how to find the kernel source git repository, complementing the other Git how-to.

Let me know if anything is unclear. Do submit a new PR if there are any immediate changes that can be made for the documentation, thanks!

p/s: I tried using a brand new VM in LXD for Noble but the build fails towards the very end; related to the ABI number and packages that cannot be found.

CC @nwager

**Comment by khbecker** [comment]
That all looks good to me. Thanks for making the modifications!

**Comment by AnneCYH** [comment]
Thanks @khbecker ! I'll close this issue then.
