### ISSUE TITLE
Signoff check fails for merge commits

### ISSUE THREAD

**Issue by gagath** [canonical/kernel-docs#35]
Since we are using merge commits instead of rebases (why?), the signoff check seems to fail on merge commits because they do not have the signoff trailers. Switching to rebase fast forward should fix this.

**Comment by AnneCYH** [comment]
hey @gagath , when you say kteam-docs uses "rebase and merge", do you mean that is typically the option that is selected (in the web UI) when someone approves & merges a PR? or are you saying there's a default setting for what happens when a PR is merged?

**Comment by AnneCYH** [comment]
Ah ok but all 3 options ("Merge pull request", "Squash and merge", and "Rebase and merge") are available in the button dropdown in both `kteam-docs` and `kernel-docs`. The option that is shown is based on the user's last selected action. 

From what I Googled there isn't a setting to actually select a "Default" option in that button for the repo. So if the intent is to enforce a specific merge request action, then the best way would be to disable the other options so they don't appear in the dropdown instead.

![image](https://github.com/user-attachments/assets/b25e4d21-afc2-4940-84ac-5ccd80a4bdf4)

And to be frank I think "Rebase and merge" should be fine; i didn't have a specific requirement for selecting "Merge pull request" (with a merge commit).

**Comment by AnneCYH** [comment]
hi @gagath , 

I think "Squash and merge" or "Rebase and merge" are the best options here depending on the PR (especially for many intermittent commits).
Unless there's a real need to "Merge pull request" (which creates an additional commit) I think removing that option in the repo settings is the best option.

What do you think?

**Comment by AnneCYH** [comment]
thanks @gagath ! I've disabled the "Merge commits" option.
