### ISSUE TITLE
linter reports working broken anchor

### ISSUE THREAD

**Issue by gagath** [canonical/kernel-docs#45]
The linter currently reports the following broken anchor in CI:

```
build finished with problems.
reference/hwe-kernels.rst:99: [broken] https://ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle: Anchor 'ubuntu-kernel-release-cycle' not found
```

However when clicking on it the anchor works:

https://ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle

It is not clear why the linter is not capable of finding the anchor. Maybe the anchor in the website is generated using some Javascript?

**Comment by AnneCYH** [comment]
The Sphinx linkcheck builder has some known issues:
https://github.com/sphinx-doc/sphinx/issues/11484

And it's not very stable; certain URLs + anchors work (though we don't know why).

we can disable the linkcheck for the anchor but check the parent URL:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_anchors_ignore_for_url

I'll add that to the spellcheck fixes branch.

**Comment by AnneCYH** [comment]
Merged: https://github.com/canonical/kernel-docs/pull/46
