### ISSUE TITLE
Migrate, review and update Stable Patch Format

### ISSUE THREAD

**Issue by AnneCYH** [canonical/kernel-docs#5]
Scope
- Migrate existing [Stable Patch Format](https://wiki.ubuntu.com/Kernel/Dev/StablePatchFormat) to RTD
- Review and update relevant content
- Reconcile with any existing content on RTD
- Restructure content according to Diataxis principles

Related pages
- https://canonical-kteam-docs.readthedocs-hosted.com/en/public/explanation/stable-release-updates.html#sru-patch-submission-and-review-process

**Comment by juergh** [comment]
We should add a reference to the [ubuntu-check-commit](https://kernel.ubuntu.com/gitea/actions/ubuntu-check-commit/src/branch/main/ubuntu-check-commit) script which we currently use for `linux-firmware` to validate proper patch formatting. I use it for kernel patches as well before sending them to the ML. It can/should be extended if it's incomplete for kernel patch checking. Probably usage changes are required. Maybe this should be a cranky subcommand...

**Comment by AnneCYH** [comment]
Hi @lkpdn , could you please take a look at the comment from @juergh about the script?
Thanks!

**Comment by lkpdn** [comment]
It's so cool! I gave it a try locally. :)
Now I'm wondering how we should validate a cover letter (from perspective of UX (User eXperience)). Anyhow, I'll include its link in my attempt of migration.
