### ISSUE TITLE
Glossary - ABI

### ISSUE THREAD

**Issue by AnneCYH** [canonical/kernel-docs#6]
Add an entry for ABI in Kernel glossary.
Entry should define what ABI stands for and provide short description of what it is.

Further improvements - To expand into a standalone Reference or Explanation.

Check existing kteam-docs content for any information about ABI.

**Comment by Jetoson** [comment]
@AnneCYH can I work on this?

**Comment by AnneCYH** [comment]
Hello @Jetoson , sure. Please feel free to assign it to yourself.

But I would suggest that maybe you could start with one issue and progressively work through the rest? :)

We are using Sphinx & RTD for this repo; let me know if you have any questions. Thanks!

**Comment by AnneCYH** [comment]
Let me know when you've decided on the issue you'd like to work on first. 
Thanks!

**Comment by Jetoson** [comment]
I would like to work on this issue first

**Comment by AnneCYH** [comment]
We haven't completed the "How to contribute" section of this docs set, apologies.
But for any updates, do create a fork, then submit a PR with the relevant updates, and add me as a reviewier.

As always, just leave a comment if you have any questions or doubts; I'll be happy to address them.

Thanks for your interest!

- Anne -

**Comment by AnneCYH** [comment]
Added in PR #12 , thanks @Jetoson !
