### ISSUE TITLE
Glossary - SRU

### ISSUE THREAD

**Issue by AnneCYH** [canonical/kernel-docs#8]
Add an entry for SRU in Kernel glossary.
Entry should define what SRU stands for and provide short description of what it is.

Link to existing Reference and/or Explanation about SRU.

Check existing kteam-docs content for any information about SRU.

**Comment by Jetoson** [comment]
@AnneCYH can I work on this?

**Comment by AnneCYH** [comment]
Completed in https://github.com/canonical/kernel-docs/pull/16.
Thanks @Jetoson
